services:
  - type: web
    name: menu-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: SPREADSHEET_ID
        value: 1KI8MaNWzYegTHrTQNOIUfD26c6b2o6vAOikY2ZqPtlg
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
